//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNN) DeepCopyInto(out *DNN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNN.
func (in *DNN) DeepCopy() *DNN {
	if in == nil {
		return nil
	}
	out := new(DNN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Free5GC) DeepCopyInto(out *Free5GC) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Free5GC.
func (in *Free5GC) DeepCopy() *Free5GC {
	if in == nil {
		return nil
	}
	out := new(Free5GC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Free5GC) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Free5GCList) DeepCopyInto(out *Free5GCList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Free5GC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Free5GCList.
func (in *Free5GCList) DeepCopy() *Free5GCList {
	if in == nil {
		return nil
	}
	out := new(Free5GCList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Free5GCList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Free5GCSpec) DeepCopyInto(out *Free5GCSpec) {
	*out = *in
	out.PFCP = in.PFCP
	in.GTPU.DeepCopyInto(&out.GTPU)
	if in.DNNList != nil {
		in, out := &in.DNNList, &out.DNNList
		*out = make([]DNN, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Free5GCSpec.
func (in *Free5GCSpec) DeepCopy() *Free5GCSpec {
	if in == nil {
		return nil
	}
	out := new(Free5GCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Free5GCStatus) DeepCopyInto(out *Free5GCStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Free5GCStatus.
func (in *Free5GCStatus) DeepCopy() *Free5GCStatus {
	if in == nil {
		return nil
	}
	out := new(Free5GCStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GTPU) DeepCopyInto(out *GTPU) {
	*out = *in
	if in.IfList != nil {
		in, out := &in.IfList, &out.IfList
		*out = make([]IfItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GTPU.
func (in *GTPU) DeepCopy() *GTPU {
	if in == nil {
		return nil
	}
	out := new(GTPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IfItem) DeepCopyInto(out *IfItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IfItem.
func (in *IfItem) DeepCopy() *IfItem {
	if in == nil {
		return nil
	}
	out := new(IfItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PFCP) DeepCopyInto(out *PFCP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PFCP.
func (in *PFCP) DeepCopy() *PFCP {
	if in == nil {
		return nil
	}
	out := new(PFCP)
	in.DeepCopyInto(out)
	return out
}
